<a href="https://colab.research.google.com/github/JeongSuHwan23/study_Data-Analysis/blob/master/0827_2214_%EC%A0%95%EC%88%98%ED%99%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = {
    '홍길동' : '010-1234-5678'
    }
a['정수환'] = '010-9190-8562'
print('홍길동' in a)
print(a)
print(a.items())
print(a.keys())

True
{'홍길동': '010-1234-5678', '정수환': '010-9190-8562'}
dict_items([('홍길동', '010-1234-5678'), ('정수환', '010-9190-8562')])
dict_keys(['홍길동', '정수환'])

In [ ]:
#딕셔러리 로그인 예제

from os import truncate

members = {'urkpo': '0928^7$',
           'xxayv': '%2*9$91',
           'lsqvx': '!0%)&&4',
           'heums': '%@3^0%3',
           'uwcmc': '85236(&',
           'iemwv': ')8!36^&',
           'sqblx': ')^2)9!(',
           'jbbpy': '67269*3',
           'hjkwu': '$&@@#64',
           'fvwwy': '82$%)31'}
flagId = 1
flagPassword = 1
while flagId or flagPassword:
  if flagId == 1:
    id = input('ID : ')
    if id in members:
      print('아이디 확인 완료')
      flagId = 0
    else:
      print('아이디를 다시 입력하세요')
      continue
  password = input('Password : ')
  if password == members.get(id):
    print('로그인 성공')
    flagPassword = 0
  else:
    print('비밀번호를 다시 입력하세요')

ID : fvwwy
아이디 확인 완료
Password : 82$%)31
로그인 성공

In [ ]:
print('주민등록번호 유효성 검사')

a = input().replace('-', '')


b = int(a[0]) * 2 + int(a[1]) * 3 + int(a[2]) * 4 + int(a[3]) * 5 + \
    int(a[4]) * 6 + int(a[5]) * 7 + int(a[6]) * 8 + int(a[7]) * 9 + \
    int(a[8]) * 2 + int(a[9]) * 3 + int(a[10]) * 4 + int(a[11]) * 5

c = b % 11
d = 11 - c

if d > 9:
    d = d - 10

if d == int(a[12]):
    print("유효한 주민등록번호입니다.")
else:
    print("유효하지 않는 주민등록번호입니다.")

주민등록번호 유효성 검사
070423-3110210
유효한 주민등록번호입니다.

In [ ]:
#분자식

atomic = {
    'H': 1,
    'C': 12,
    'O': 16,
    'N': 14
}

molecular = input("분자식을 입력하세요: ")

i = 0
weight = 0

while i < len(molecular):
    e = molecular[i]
    i += 1
    quantity = 0
    while i < len(molecular) and molecular[i].isdigit():
        quantity = quantity * 10 + int(molecular[i])
        i += 1
    if quantity == 0:
        quantity = 1
    weight += atomic[e] * quantity

print(weight)

분자식을 입력하세요: H2O
18

In [ ]:
#프로젝트 : 전화번호

user = {}
flag = 1
while flag:
  print('1 : 전화번호 등록')
  print('2 : 전화번호 삭제')
  print('3 : 전화번호 검색')
  print('4 : 전화번호 전체 보기')
  print('5 : 종료')
  n = input()
  if(n == '1'):
    u = input('이름:전화번호 형태로 입력 >> ')
    user[u[0:3]] = u[4:]
  elif(n == '2'):
    u = input('이름 입력 : ')
    del(user[u])
  elif(n == '3'):
    u = input('이름 입력 : ')
    print(user.get(u))
  elif(n == '4'):
    print(user)
  elif(n == '5'):
    print('종료')
    flag = 0

1 : 전화번호 등록
2 : 전화번호 삭제
3 : 전화번호 검색
4 : 전화번호 전체 보기
5 : 종료
5
종료

In [ ]:
import pandas as pd
url = 'https://www.koreabaseball.com/Record/Player/HitterBasic/BasicOld.aspx'
tables = pd.read_html( url )
tables[0].to_excel("KBO_타자기록.xlsx")
df = pd.DataFrame( tables[0] )
df.head()

In [ ]:
import pandas as pd
import numpy as np

s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [ ]:
data = {
    'year':[2016, 2017, 2018],
    'GDP rate': [2.8, 3.1, 3.0],
    'GDP': ['1.637M', '1.73M', '1.83M' ]
}
df = pd.DataFrame(data)
print(df)

   year  GDP rate     GDP
0  2016       2.8  1.637M
1  2017       3.1   1.73M
2  2018       3.0   1.83M

In [ ]:
df.head()

   year  GDP rate     GDP
0  2016       2.8  1.637M
1  2017       3.1   1.73M
2  2018       3.0   1.83M

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   year      3 non-null      int64
 1   GDP rate  3 non-null      float64
 2   GDP       3 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 200.0+ bytes

In [ ]:
df.describe()

<bound method NDFrame.describe of    year  GDP rate     GDP
0  2016       2.8  1.637M
1  2017       3.1   1.73M
2  2018       3.0   1.83M>